name: ml
channels:
  - defaults
dependencies:
  - tensorflow-gpu
  - keras-gpu
  - pytorch
  # - torchvision
  - jupyter
  - matplotlib 
  # - tqdm  # nice progress bars
  # - other packages you want to use
  # - 
  # if you have some package that is not on conda but is on pip:
  # - pip
  # - pip:
    # - some_pip_only_package
